import 'package:flutter/services.dart';

/// Credentials of a running local-only hotspot (system-generated).
class HotspotInfo {
  final String ssid;
  final String password;

  /// Radio band label (e.g. "2.4 GHz"), or null if unknown.
  final String? band;

  const HotspotInfo({
    required this.ssid,
    required this.password,
    this.band,
  });
}

/// Dart facade over the native local-only Wi-Fi hotspot probe.
///
/// Backed by `WifiManager.startLocalOnlyHotspot` — the SSID and password are
/// generated by the system (not configurable) and no internet is shared.
class HotspotService {
  static const _channel = MethodChannel('ebadge/wifi');

  /// Start (or fetch the already-running) hotspot and return its credentials.
  /// Throws [PlatformException] on failure (unsupported OS, missing location
  /// permission, incompatible mode, …).
  Future<HotspotInfo> start() async {
    final res = await _channel.invokeMapMethod<String, dynamic>('startHotspot');
    return HotspotInfo(
      ssid: res?['ssid'] as String? ?? '',
      password: res?['password'] as String? ?? '',
      band: res?['band'] as String?,
    );
  }

  Future<void> stop() => _channel.invokeMethod('stopHotspot');

  Future<bool> isActive() async =>
      await _channel.invokeMethod<bool>('isHotspotActive') ?? false;
}
